# Example GO_CD YAML configuration
format_version: 5
environments:
  dev1:
    environment_variables:
      ENVIRONMENT: dev1
  test:
    environment_variables:
      ENVIRONMENT: test
  prod:
    environment_variables:
      ENVIRONMENT: prod
pipelines:
  service1:
    group: "01-Acquistion"
    parameters:
      param1: version
    materials:
      getting_started_repo:
        git: https://github.com/gocd-contrib/getting-started-repo.git
        branch: master
    stages:
      - package:
          jobs:
            build:
              tasks:
                - script: 'echo "[Packaging] Service: ${GO_PIPELINE_NAME}" - ${GO_PIPELINE_COUNTER}'
      - deploy:
          jobs:
            build:
              tasks:
                - script: 'echo "[Deploying] Service: ${GO_PIPELINE_NAME}" - ${GO_PIPELINE_COUNTER}'
  service2:
    group: "01-Acquistion"
    parameters:
      param2: version
    materials:
      getting_started_repo:
        git: https://github.com/gocd-contrib/getting-started-repo.git
        branch: master
    stages:
      - package:
          jobs:
            build:
              tasks:
                - script: 'echo "[Packaging] Service: ${GO_PIPELINE_NAME}" - ${GO_PIPELINE_COUNTER}'
      - deploy:
          jobs:
            build:
              tasks:
                - script: 'echo "[Deploying] Service: ${GO_PIPELINE_NAME}" - ${GO_PIPELINE_COUNTER}'
