# Example GO_CD YAML configuration
format_version: 5
environments:
  development:
    environment_variables:
      environment: dev1
pipelines:
  testpipe:
    group: poc
    materials:
      getting_started_repo:
        git: https://github.com/gocd-contrib/getting-started-repo.git
        branch: master
    stages:
      - build:
          jobs:
            build:
              tasks:
                - script: ./build
